language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
before_script:
  - sudo apt-get install pychecker
install:
  - pip install pybuilder pyfix
  - pyb --debug install_dependencies
script: "pyb --debug publish"
notifications:
  email:
    - arne.hilmann@immobilienscout24.de
    - michael.gruber@immobilienscout24.de
    - maximilien.riehl@immobilienscout24.de
